export default {
  mod: { display: 'flex', alignItems: 'flex-end', flexDirection: 'column', width: '238px', height: '109px' },
  bd: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '238px',
    height: '68px',
  },
  actionBg: { position: 'absolute', top: '0px', left: '0px', width: '238px', height: '68px' },
  info: {
    position: 'relative',
    opacity: 1,
    marginRight: '12px',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    color: '#00ffff',
    fontSize: '18px',
    fontWeight: 500,
  },
  icon: { position: 'relative', width: '28px', height: '16px' },
  ft: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '17px',
    width: '153px',
    height: '22px',
  },
  wrap: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '22px' },
  empty: {
    marginRight: '10px',
    borderWidth: '3px',
    borderStyle: 'solid',
    borderRadius: '16px',
    borderColor: 'rgba(0, 255, 255, 1.00)',
    width: '16px',
    height: '16px',
  },
  word: {
    opacity: 1,
    maxWidth: '46px',
    height: '22px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '18px',
    fontWeight: 400,
  },
  block: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '22px' },
  div: {
    marginRight: '10px',
    borderWidth: '3px',
    borderStyle: 'solid',
    borderRadius: '16px',
    borderColor: 'rgba(255, 0, 77, 1.00)',
    width: '16px',
    height: '16px',
  },
  text: {
    opacity: 1,
    maxWidth: '37px',
    height: '22px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '18px',
    fontWeight: 400,
  },
};
